import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "vi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved === "en" || saved === "vi" ? saved : "vi") as Language;
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === "object" && k in value) {
        value = value[k];
      } else {
        return key; // Return key if translation not found
      }
    }
    
    return typeof value === "string" ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations = {
  en: {
    nav: {
      dashboard: "Dashboard",
      competitions: "Competitions",
      students: "Student Data",
      certificates: "Certificate Processing",
      match: "Match & Review",
      drive: "Drive Sync",
      email: "Email Campaigns",
      logs: "Logs",
      settings: "Settings",
    },
    header: {
      newProcess: "New Process",
      googleConnected: "Google Connected",
      selectCompetition: "Select Competition",
      newCompetition: "New Competition",
    },
    dashboard: {
      title: "Dashboard",
      subtitle: "Overview of Math Olympiad 2026",
      totalStudents: "Total Students",
      certificatesProcessed: "Certificates Processed",
      emailsSent: "Emails Sent",
      driveFiles: "Drive Files",
      fromLastMonth: "from last month",
      recentActivities: "Recent Activities",
      latestProcessing: "Latest processing activities",
      pendingTasks: "Pending Tasks",
      actionsRequired: "Actions requiring attention",
      quickActions: "Quick Actions",
      commonWorkflows: "Common workflows to get started",
      uploadCertificates: "Upload Certificates",
      syncStudentData: "Sync Student Data",
      reviewMatches: "Review Matches",
      sendEmails: "Send Emails",
      certificateBatchProcessed: "Certificate batch processed",
      emailCampaignSent: "Email campaign sent",
      driveSyncInProgress: "Drive sync in progress",
      matchReviewPending: "Match review pending",
      hoursAgo: "hours ago",
      justNow: "Just now",
      dayAgo: "day ago",
      reviewUnmatched: "Review unmatched certificates",
      retryFailed: "Retry failed email sends",
      updateStudent: "Update student data from Sheets",
      configureNaming: "Configure file naming rules",
      items: "items",
    },
    competitions: {
      title: "Competition Setup",
      subtitle: "Configure competition details and integrations",
      competitionInfo: "Competition Information",
      basicDetails: "Basic details about this competition",
      competitionName: "Competition Name",
      academicYear: "Academic Year / Season",
      competitionType: "Competition Type",
      subject: "Subject / Category",
      emailTemplate: "Email Template",
      folderNaming: "Folder Naming Rule",
      fileNaming: "File Naming Rule",
      googleSheets: "Google Sheets",
      studentDataSource: "Student data source",
      googleDrive: "Google Drive",
      certificateStorage: "Certificate storage",
      gmailService: "Gmail Service",
      emailDelivery: "Email delivery",
      status: "Status",
      connected: "Connected",
      account: "Account",
      lastSync: "Last Sync",
      lastUpload: "Last Upload",
      lastSend: "Last Send",
      sheetId: "Sheet ID",
      destinationFolder: "Destination Folder",
      dailyQuota: "Daily Quota",
      reconnect: "Reconnect",
      configureMapping: "Configure Mapping",
      openFolder: "Open Folder",
      testEmail: "Test Email",
      cancel: "Cancel",
      saveConfiguration: "Save Configuration",
      olympiad: "Olympiad",
      contest: "Contest",
      exam: "Exam",
      fair: "Fair",
      mathematics: "Mathematics",
      physics: "Physics",
      chemistry: "Chemistry",
      biology: "Biology",
      english: "English",
      informatics: "Informatics",
      defaultTemplate: "Default Template",
      formalTemplate: "Formal Template",
      friendlyTemplate: "Friendly Template",
    },
    students: {
      title: "Student Data",
      registered: "students registered",
      syncFromSheets: "Sync from Sheets",
      export: "Export",
      searchPlaceholder: "Search by name, email, or certificate code...",
      filterByAward: "Filter by award",
      filterByStatus: "Filter by status",
      allAwards: "All Awards",
      goldMedal: "Gold Medal",
      silverMedal: "Silver Medal",
      bronzeMedal: "Bronze Medal",
      consolationPrize: "Consolation Prize",
      allStatus: "All Status",
      emailSent: "Email Sent",
      pending: "Pending",
      failed: "Failed",
      emailsSent: "Emails Sent",
      missingEmail: "Missing Email",
      missingCertificate: "Missing Certificate",
      studentList: "Student List",
      showing: "Showing",
      of: "of",
      students: "students",
      studentId: "Student ID",
      name: "Name",
      email: "Email",
      school: "School",
      grade: "Grade",
      award: "Award",
      certCode: "Cert Code",
      mailStatus: "Mail Status",
      actions: "Actions",
      missing: "Missing",
      sent: "Sent",
      view: "View",
    },
    certificates: {
      title: "Certificate Processing",
      subtitle: "Upload and process certificate PDFs",
      uploadCertificates: "Upload Certificates",
      dragDropMessage: "Drag and drop PDF files or click to browse",
      dropMessage: "Drop your certificate PDFs here",
      browseMessage: "or click to browse your computer",
      selectFiles: "Select PDF Files",
      uploadedFiles: "Uploaded Files",
      filesReady: "Files ready for processing",
      pages: "pages",
      completed: "Completed",
      processing: "Processing",
      extractingData: "Extracting data from certificates...",
      processingMode: "Processing Mode",
      selectOperations: "Select what operations to perform",
      splitOnly: "Split Only",
      splitOnlyDesc: "Just split PDF into individual pages",
      splitExtract: "Split + Extract",
      splitExtractDesc: "Split and extract certificate information",
      splitExtractMatch: "Split + Extract + Match",
      splitExtractMatchDesc: "Also match certificates to students",
      fullPipeline: "Full Pipeline",
      fullPipelineDesc: "Complete workflow: Split → Extract → Upload → Update Sheet",
      additionalOptions: "Additional Options",
      fineTuneProcessing: "Fine-tune processing behavior",
      detectDuplicates: "Detect duplicate certificate code",
      detectDuplicatesDesc: "Flag certificates with same code",
      normalizeNames: "Normalize student names",
      normalizeNamesDesc: "Standardize name formatting",
      normalizeSchools: "Normalize school names",
      normalizeSchoolsDesc: "Remove special characters",
      runValidation: "Run validation rules",
      runValidationDesc: "Check for common errors",
      overwriteLinks: "Overwrite existing Drive links",
      overwriteLinksDesc: "Replace files already uploaded",
      saveUnmatched: "Save unmatched certificates",
      saveUnmatchedDesc: "To a separate folder for review",
      processingPipeline: "Processing Pipeline",
      currentWorkflowStatus: "Current workflow status",
      upload: "Upload",
      splitPages: "Split Pages",
      extractData: "Extract Data",
      matchStudents: "Match Students",
      uploadToDrive: "Upload to Drive",
      updateGoogleSheet: "Update Google Sheet",
      readyForEmail: "Ready for Email",
      startProcessing: "Start Processing",
    },
    match: {
      title: "Match & Review",
      subtitle: "Confirm certificate to student mapping",
      totalProcessed: "Total Processed",
      matched: "Matched",
      unmatched: "Unmatched",
      warnings: "Warnings",
      readyToUpload: "Ready to Upload",
      readyToEmail: "Ready to Email",
      allMatches: "All Matches",
      highConfidence: "High Confidence",
      mediumConfidence: "Medium Confidence",
      unmatchedOnly: "Unmatched Only",
      selected: "selected",
      approveSelected: "Approve Selected",
      approveAllHigh: "Approve All High Confidence",
      uploadToDrive: "Upload to Drive",
      certificateMatching: "Certificate Matching",
      reviewAndConfirm: "Review and confirm certificate to student assignments",
      preview: "Preview",
      extractedName: "Extracted Name",
      award: "Award",
      certCode: "Cert Code",
      matchedStudent: "Matched Student",
      email: "Email",
      confidence: "Confidence",
      status: "Status",
      actions: "Actions",
      noMatch: "No match",
      high: "High",
      medium: "Medium",
      low: "Low",
      drive: "Drive",
      sheet: "Sheet",
      certificateMatchDetails: "Certificate Match Details",
      reviewCertificate: "Review certificate and student information",
      certificateData: "Certificate Data",
      matchedStudentData: "Matched Student",
      studentId: "Student ID",
      notMatched: "Not matched",
      name: "Name",
      subject: "Subject",
      code: "Code",
      approveMatch: "Approve Match",
      changeStudent: "Change Student",
      markAsUnmatched: "Mark as Unmatched",
    },
    drive: {
      title: "Drive Sync",
      subtitle: "Manage certificate uploads and sheet updates",
      openDriveFolder: "Open Drive Folder",
      reconnect: "Reconnect",
      uploaded: "Uploaded",
      pending: "Pending",
      failed: "Failed",
      sheetUpdated: "Sheet Updated",
      updateFailed: "Update Failed",
      googleSheetsMapping: "Google Sheets Mapping",
      configureMatching: "Configure how to match certificates with sheet rows",
      googleSheetId: "Google Sheet ID",
      worksheetName: "Worksheet Name",
      matchingField: "Matching Field",
      certificateCode: "Certificate Code",
      studentId: "Student ID",
      email: "Email",
      compositeMatch: "Name + Award + Subject",
      studentNameColumn: "Student Name Column",
      emailColumn: "Email Column",
      awardColumn: "Award Column",
      certCodeColumn: "Cert Code Column",
      fileUrlColumn: "File URL Column",
      mailStatusColumn: "Mail Status Column",
      testMapping: "Test Mapping",
      saveConfiguration: "Save Configuration",
      syncActivity: "Sync Activity",
      uploadAndSheetHistory: "Upload and sheet update history",
      retryFailedUploads: "Retry Failed Uploads",
      retrySheetUpdates: "Retry Sheet Updates",
      studentName: "Student Name",
      certCode: "Cert Code",
      fileName: "File Name",
      driveStatus: "Drive Status",
      sheetRow: "Sheet Row",
      sheetStatus: "Sheet Status",
      lastAttempt: "Last Attempt",
      actions: "Actions",
      row: "Row",
    },
    email: {
      title: "Email Campaigns",
      subtitle: "Send certificates to students via email",
      totalRecipients: "Total Recipients",
      readyToSend: "Ready to Send",
      missingCertificate: "Missing Certificate",
      missingEmail: "Missing Email",
      sent: "Sent",
      failed: "Failed",
      filters: "Filters",
      filterRecipients: "Filter recipients by status",
      allRecipients: "All Recipients",
      readyToSendFilter: "Ready to Send",
      alreadySent: "Already Sent",
      missingEmailFilter: "Missing Email",
      missingCertificateFilter: "Missing Certificate",
      recipients: "Recipients",
      selected: "selected",
      selectAll: "Select All",
      deselectAll: "Deselect All",
      student: "Student",
      email: "Email",
      award: "Award",
      status: "Status",
      missing: "Missing",
      ready: "Ready",
      pending: "Pending",
      emailComposer: "Email Composer",
      composeMessage: "Compose your email message",
      emailTemplate: "Email Template",
      defaultTemplate: "Default Template",
      formalTemplate: "Formal Template",
      friendlyTemplate: "Friendly Template",
      subjectLine: "Subject Line",
      messageBody: "Message Body",
      availableMergeTags: "Available Merge Tags",
      studentName: "Student's full name",
      awardReceived: "Award received",
      competitionSubject: "Competition subject",
      certificateLink: "Link to certificate",
      schoolName: "Student's school",
      competitionName: "Competition name",
      sendAsAttachment: "Send as attachment",
      attachPdfDirectly: "Attach PDF directly to email",
      sendAsDriveLink: "Send as Drive link",
      includeDriveLink: "Include Google Drive link",
      ccOrganizer: "CC organizer",
      sendCopyToAdmin: "Send copy to admin",
      previewEmail: "Preview Email",
      saveTemplate: "Save Template",
      sendTestEmail: "Send Test Email",
      sendToSelected: "Send to Selected",
      sendToAllReady: "Send to All Ready",
      emailPreview: "Email Preview",
      previewWithSample: "Preview with sample merge field values",
      to: "To",
      subject: "Subject",
    },
    logs: {
      title: "Logs",
      subtitle: "Track all automation activities",
      searchLogs: "Search logs...",
      export: "Export",
      processed: "Processed",
      successful: "Successful",
      failed: "Failed",
      warnings: "Warnings",
      activityLogs: "Activity Logs",
      detailedAuditTrail: "Detailed audit trail of all operations",
      processingLogs: "Processing Logs",
      uploadLogs: "Upload Logs",
      sheetUpdateLogs: "Sheet Update Logs",
      emailLogs: "Email Logs",
      errorsOnly: "Errors Only",
      timestamp: "Timestamp",
      action: "Action",
      studentName: "Student Name",
      certCode: "Cert Code",
      result: "Result",
      details: "Details",
      actions: "Actions",
      success: "Success",
      warning: "Warning",
      studentProcessingTimeline: "Student Processing Timeline",
      completeAuditTrail: "Complete audit trail for",
      certificateMatched: "Certificate Matched",
      matchedWithHighConfidence: "Matched with high confidence to student record",
      uploadedToDrive: "Uploaded to Drive",
      fileUploadedSuccessfully: "File uploaded successfully to Google Drive",
      sheetUpdated: "Sheet Updated",
      fileUrlWrittenToSheet: "File URL written to Google Sheets row",
      emailSent: "Email Sent",
      certificateEmailSent: "Certificate email sent to",
    },
    settings: {
      title: "Settings",
      subtitle: "Configure system behavior and integrations",
      fileNaming: "File Naming",
      matchingRules: "Matching Rules",
      validation: "Validation",
      integrations: "Integrations",
      fileNamingRules: "File Naming Rules",
      configureFileNames: "Configure how certificate files should be named",
      prettyFormat: "Pretty File Name Format",
      prettyFormatDesc: "Used for display purposes. Supports: {student_name}, {award}, {subject}, {school}, {grade}, {cert_code}",
      safeFormat: "Safe System File Name Format",
      safeFormatDesc: "Used for actual file storage. Special characters will be removed automatically.",
      maxFileLength: "Maximum File Name Length",
      characters: "characters",
      transliterateVietnamese: "Transliterate Vietnamese Characters",
      transliterateVietnameseDesc: "Convert \"Nguyễn\" to \"Nguyen\", \"Đỗ\" to \"Do\", etc.",
      replaceSpaces: "Replace Spaces with Underscores",
      replaceSpacesDesc: "More compatible with some systems",
      convertToLowercase: "Convert to Lowercase",
      convertToLowercaseDesc: "All file names in lowercase",
      saveFileNamingRules: "Save File Naming Rules",
      studentMatchingRules: "Student Matching Rules",
      howToMatchCertificates: "How to match certificates to student records",
      exactCertCodeMatch: "Exact Certificate Code Match",
      exactCertCodeMatchDesc: "Match by certificate code when available",
      exactStudentIdMatch: "Exact Student ID Match",
      exactStudentIdMatchDesc: "Match by student ID when code unavailable",
      fuzzyNameMatch: "Fuzzy Student Name Match",
      fuzzyNameMatchDesc: "Allow minor spelling variations",
      verifyAwardSubject: "Verify Award and Subject",
      verifyAwardSubjectDesc: "Must match expected award and subject",
      confidenceThreshold: "Confidence Threshold",
      confidenceThresholdDesc: "Minimum confidence score to auto-approve a match",
      fuzzyMatchTolerance: "Fuzzy Match Tolerance",
      fuzzyMatchToleranceDesc: "String similarity required for fuzzy name matching",
      saveMatchingRules: "Save Matching Rules",
      validationRules: "Validation Rules",
      detectCommonErrors: "Detect common errors and anomalies",
      detectTypoQualified: "Detect Typo \"Qualifed\" (Missing 'i')",
      detectTypoQualifiedDesc: "Common OCR error in certificate text",
      detectCaseAnomalies: "Detect Uppercase/Lowercase Anomalies",
      detectCaseAnomaliesDesc: "Flag inconsistent capitalization",
      detectSchoolPipe: "Detect School Name Contains \"|\"",
      detectSchoolPipeDesc: "Common OCR error for \"l\" or \"I\"",
      detectMissingAward: "Detect Missing Award",
      detectMissingAwardDesc: "Certificate without award information",
      detectDuplicateFiles: "Detect Duplicate File Names",
      detectDuplicateFilesDesc: "Warn about potential overwrite conflicts",
      detectDuplicateCertCode: "Detect Duplicate Certificate Code",
      detectDuplicateCertCodeDesc: "Same code used for multiple certificates",
      checkMissingEmail: "Check for Missing Email Addresses",
      checkMissingEmailDesc: "Flag students without email before sending",
      validateEmailFormat: "Validate Email Format",
      validateEmailFormatDesc: "Check email addresses are properly formatted",
      saveValidationRules: "Save Validation Rules",
      googleDriveApi: "Google Drive API",
      configureDriveIntegration: "Configure Google Drive integration",
      clientId: "Client ID",
      clientSecret: "Client Secret",
      redirectUri: "Redirect URI",
      testConnection: "Test Connection",
      googleSheetsApi: "Google Sheets API",
      configureSheetsIntegration: "Configure Google Sheets integration",
      apiKey: "API Key",
      serviceAccountEmail: "Service Account Email",
      gmailEmailService: "Gmail / Email Service",
      configureEmailService: "Configure email sending service",
      serviceType: "Service Type",
      gmailApi: "Gmail API",
      googleAppsScript: "Google Apps Script",
      sendGrid: "SendGrid",
      smtp: "SMTP",
      fromEmail: "From Email",
      fromName: "From Name",
      webhookEndpoint: "Webhook Endpoint",
      optionalWebhook: "Optional webhook for external integrations",
      webhookUrl: "Webhook URL",
      secretKey: "Secret Key",
      enableWebhook: "Enable Webhook",
      sendEventsToExternal: "Send events to external endpoint",
      saveIntegrationSettings: "Save Integration Settings",
    },
    common: {
      ago: "ago",
      minute: "minute",
      minutes: "minutes",
      hour: "hour",
      hours: "hours",
      day: "day",
      days: "days",
    },
  },
  vi: {
    nav: {
      dashboard: "Bảng điều khiển",
      competitions: "Cuộc thi",
      students: "Dữ liệu học sinh",
      certificates: "Xử lý chứng chỉ",
      match: "Ghép & Xem xét",
      drive: "Đồng bộ Drive",
      email: "Chiến dịch Email",
      logs: "Nhật ký",
      settings: "Cài đặt",
    },
    header: {
      newProcess: "Quy trình mới",
      googleConnected: "Đã kết nối Google",
      selectCompetition: "Chọn cuộc thi",
      newCompetition: "Cuộc thi mới",
    },
    dashboard: {
      title: "Bảng điều khiển",
      subtitle: "Tổng quan Olympic Toán 2026",
      totalStudents: "Tổng số học sinh",
      certificatesProcessed: "Chứng chỉ đã xử lý",
      emailsSent: "Email đã gửi",
      driveFiles: "Tệp Drive",
      fromLastMonth: "so với tháng trước",
      recentActivities: "Hoạt động gần đây",
      latestProcessing: "Các hoạt động xử lý mới nhất",
      pendingTasks: "Nhiệm vụ đang chờ",
      actionsRequired: "Các hành động cần chú ý",
      quickActions: "Hành động nhanh",
      commonWorkflows: "Quy trình thông dụng để bắt đầu",
      uploadCertificates: "Tải lên chứng chỉ",
      syncStudentData: "Đồng bộ dữ liệu học sinh",
      reviewMatches: "Xem xét kết quả ghép",
      sendEmails: "Gửi Email",
      certificateBatchProcessed: "Đã xử lý lô chứng chỉ",
      emailCampaignSent: "Đã gửi chiến dịch email",
      driveSyncInProgress: "Đang đồng bộ Drive",
      matchReviewPending: "Chờ xem xét kết quả ghép",
      hoursAgo: "giờ trước",
      justNow: "Vừa xong",
      dayAgo: "ngày trước",
      reviewUnmatched: "Xem xét chứng chỉ chưa ghép",
      retryFailed: "Thử lại gửi email thất bại",
      updateStudent: "Cập nhật dữ liệu học sinh từ Sheets",
      configureNaming: "Cấu hình quy tắc đặt tên file",
      items: "mục",
    },
    competitions: {
      title: "Thiết lập cuộc thi",
      subtitle: "Cấu hình chi tiết cuộc thi và tích hợp",
      competitionInfo: "Thông tin cuộc thi",
      basicDetails: "Chi tiết cơ bản về cuộc thi này",
      competitionName: "Tên cuộc thi",
      academicYear: "Năm học / Mùa",
      competitionType: "Loại cuộc thi",
      subject: "Môn / Danh mục",
      emailTemplate: "Mẫu email",
      folderNaming: "Quy tắc đặt tên thư mục",
      fileNaming: "Quy tắc đặt tên file",
      googleSheets: "Google Sheets",
      studentDataSource: "Nguồn dữ liệu học sinh",
      googleDrive: "Google Drive",
      certificateStorage: "Lưu trữ chứng chỉ",
      gmailService: "Dịch vụ Gmail",
      emailDelivery: "Gửi email",
      status: "Trạng thái",
      connected: "Đã kết nối",
      account: "Tài khoản",
      lastSync: "Đồng bộ lần cuối",
      lastUpload: "Tải lên lần cuối",
      lastSend: "Gửi lần cuối",
      sheetId: "ID Sheet",
      destinationFolder: "Thư mục đích",
      dailyQuota: "Hạn ngạch hàng ngày",
      reconnect: "Kết nối lại",
      configureMapping: "Cấu hình ánh xạ",
      openFolder: "Mở thư mục",
      testEmail: "Gửi email thử",
      cancel: "Hủy",
      saveConfiguration: "Lưu cấu hình",
      olympiad: "Olympic",
      contest: "Cuộc thi",
      exam: "Kỳ thi",
      fair: "Hội thi",
      mathematics: "Toán học",
      physics: "Vật lý",
      chemistry: "Hóa học",
      biology: "Sinh học",
      english: "Tiếng Anh",
      informatics: "Tin học",
      defaultTemplate: "Mẫu mặc định",
      formalTemplate: "Mẫu trang trọng",
      friendlyTemplate: "Mẫu thân thiện",
    },
    students: {
      title: "Dữ liệu học sinh",
      registered: "học sinh đã đăng ký",
      syncFromSheets: "Đồng bộ từ Sheets",
      export: "Xuất dữ liệu",
      searchPlaceholder: "Tìm theo tên, email hoặc mã chứng chỉ...",
      filterByAward: "Lọc theo giải thưởng",
      filterByStatus: "Lọc theo trạng thái",
      allAwards: "Tất cả giải thưởng",
      goldMedal: "Huy chương Vàng",
      silverMedal: "Huy chương Bạc",
      bronzeMedal: "Huy chương Đồng",
      consolationPrize: "Giải Khuyến khích",
      allStatus: "Tất cả trạng thái",
      emailSent: "Đã gửi Email",
      pending: "Đang chờ",
      failed: "Thất bại",
      emailsSent: "Email đã gửi",
      missingEmail: "Thiếu Email",
      missingCertificate: "Thiếu chứng chỉ",
      studentList: "Danh sách học sinh",
      showing: "Hiển thị",
      of: "trên",
      students: "học sinh",
      studentId: "Mã học sinh",
      name: "Họ tên",
      email: "Email",
      school: "Trường",
      grade: "Lớp",
      award: "Giải thưởng",
      certCode: "Mã chứng chỉ",
      mailStatus: "Trạng thái Email",
      actions: "Hành động",
      missing: "Thiếu",
      sent: "Đã gửi",
      view: "Xem",
    },
    certificates: {
      title: "Xử lý chứng chỉ",
      subtitle: "Tải lên và xử lý PDF chứng chỉ",
      uploadCertificates: "Tải lên chứng chỉ",
      dragDropMessage: "Kéo thả file PDF hoặc nhấp để duyệt",
      dropMessage: "Thả PDF chứng chỉ của bạn vào đây",
      browseMessage: "hoặc nhấp để duyệt máy tính của bạn",
      selectFiles: "Chọn file PDF",
      uploadedFiles: "File đã tải lên",
      filesReady: "File sẵn sàng để xử lý",
      pages: "trang",
      completed: "Hoàn thành",
      processing: "Đang xử lý",
      extractingData: "Đang trích xuất dữ liệu từ chứng chỉ...",
      processingMode: "Chế độ xử lý",
      selectOperations: "Chọn các thao tác cần thực hiện",
      splitOnly: "Chỉ tách",
      splitOnlyDesc: "Chỉ tách PDF thành các trang riêng lẻ",
      splitExtract: "Tách + Trích xuất",
      splitExtractDesc: "Tách và trích xuất thông tin chứng chỉ",
      splitExtractMatch: "Tách + Trích xuất + Ghép",
      splitExtractMatchDesc: "Cũng ghép chứng chỉ với học sinh",
      fullPipeline: "Quy trình đầy đủ",
      fullPipelineDesc: "Quy trình hoàn chỉnh: Tách → Trích xuất → Tải lên → Cập nhật Sheet",
      additionalOptions: "Tùy chọn bổ sung",
      fineTuneProcessing: "Điều chỉnh chi tiết xử lý",
      detectDuplicates: "Phát hiện mã chứng chỉ trùng lặp",
      detectDuplicatesDesc: "Đánh dấu chứng chỉ có cùng mã",
      normalizeNames: "Chuẩn hóa tên học sinh",
      normalizeNamesDesc: "Tiêu chuẩn hóa định dạng tên",
      normalizeSchools: "Chuẩn hóa tên trường",
      normalizeSchoolsDesc: "Xóa ký tự đặc biệt",
      runValidation: "Chạy quy tắc xác thực",
      runValidationDesc: "Kiểm tra lỗi thường gặp",
      overwriteLinks: "Ghi đè link Drive hiện có",
      overwriteLinksDesc: "Thay thế file đã tải lên",
      saveUnmatched: "Lưu chứng chỉ chưa ghép",
      saveUnmatchedDesc: "Vào thư mục riêng để xem xét",
      processingPipeline: "Quy trình xử lý",
      currentWorkflowStatus: "Trạng thái quy trình hiện tại",
      upload: "Tải lên",
      splitPages: "Tách trang",
      extractData: "Trích xuất dữ liệu",
      matchStudents: "Ghép học sinh",
      uploadToDrive: "Tải lên Drive",
      updateGoogleSheet: "Cập nhật Google Sheet",
      readyForEmail: "Sẵn sàng gửi Email",
      startProcessing: "Bắt đầu xử lý",
    },
    match: {
      title: "Ghép & Xem xét",
      subtitle: "Xác nhận ánh xạ chứng chỉ với học sinh",
      totalProcessed: "Tổng đã xử lý",
      matched: "Đã ghép",
      unmatched: "Chưa ghép",
      warnings: "Cảnh báo",
      readyToUpload: "Sẵn sàng tải lên",
      readyToEmail: "Sẵn sàng gửi Email",
      allMatches: "Tất cả kết quả",
      highConfidence: "Độ tin cậy cao",
      mediumConfidence: "Độ tin cậy trung bình",
      unmatchedOnly: "Chỉ chưa ghép",
      selected: "đã chọn",
      approveSelected: "Duyệt đã chọn",
      approveAllHigh: "Duyệt tất cả độ tin cậy cao",
      uploadToDrive: "Tải lên Drive",
      certificateMatching: "Ghép chứng chỉ",
      reviewAndConfirm: "Xem xét và xác nhận phân công chứng chỉ cho học sinh",
      preview: "Xem trước",
      extractedName: "Tên trích xuất",
      award: "Giải thưởng",
      certCode: "Mã chứng chỉ",
      matchedStudent: "Học sinh ghép",
      email: "Email",
      confidence: "Độ tin cậy",
      status: "Trạng thái",
      actions: "Hành động",
      noMatch: "Không ghép",
      high: "Cao",
      medium: "Trung bình",
      low: "Thấp",
      drive: "Drive",
      sheet: "Sheet",
      certificateMatchDetails: "Chi tiết ghép chứng chỉ",
      reviewCertificate: "Xem xét thông tin chứng chỉ và học sinh",
      certificateData: "Dữ liệu chứng chỉ",
      matchedStudentData: "Học sinh ghép",
      studentId: "Mã học sinh",
      notMatched: "Chưa ghép",
      name: "Tên",
      subject: "Môn",
      code: "Mã",
      approveMatch: "Duyệt ghép",
      changeStudent: "Đổi học sinh",
      markAsUnmatched: "Đánh dấu chưa ghép",
    },
    drive: {
      title: "Đồng bộ Drive",
      subtitle: "Quản lý tải lên chứng chỉ và cập nhật sheet",
      openDriveFolder: "Mở thư mục Drive",
      reconnect: "Kết nối lại",
      uploaded: "Đã tải lên",
      pending: "Đang chờ",
      failed: "Thất bại",
      sheetUpdated: "Đã cập nhật Sheet",
      updateFailed: "Cập nhật thất bại",
      googleSheetsMapping: "Ánh xạ Google Sheets",
      configureMatching: "Cấu hình cách ghép chứng chỉ với hàng sheet",
      googleSheetId: "ID Google Sheet",
      worksheetName: "Tên Worksheet",
      matchingField: "Trường ghép",
      certificateCode: "Mã chứng chỉ",
      studentId: "Mã học sinh",
      email: "Email",
      compositeMatch: "Tên + Giải + Môn",
      studentNameColumn: "Cột tên học sinh",
      emailColumn: "Cột Email",
      awardColumn: "Cột giải thưởng",
      certCodeColumn: "Cột mã chứng chỉ",
      fileUrlColumn: "Cột URL file",
      mailStatusColumn: "Cột trạng thái Email",
      testMapping: "Kiểm tra ánh xạ",
      saveConfiguration: "Lưu cấu hình",
      syncActivity: "Hoạt động đồng bộ",
      uploadAndSheetHistory: "Lịch sử tải lên và cập nhật sheet",
      retryFailedUploads: "Thử lại tải lên thất bại",
      retrySheetUpdates: "Thử lại cập nhật Sheet",
      studentName: "Tên học sinh",
      certCode: "Mã chứng chỉ",
      fileName: "Tên file",
      driveStatus: "Trạng thái Drive",
      sheetRow: "Hàng Sheet",
      sheetStatus: "Trạng thái Sheet",
      lastAttempt: "Lần thử cuối",
      actions: "Hành động",
      row: "Hàng",
    },
    email: {
      title: "Chiến dịch Email",
      subtitle: "Gửi chứng chỉ cho học sinh qua email",
      totalRecipients: "Tổng người nhận",
      readyToSend: "Sẵn sàng gửi",
      missingCertificate: "Thiếu chứng chỉ",
      missingEmail: "Thiếu Email",
      sent: "Đã gửi",
      failed: "Thất bại",
      filters: "Bộ lọc",
      filterRecipients: "Lọc người nhận theo trạng thái",
      allRecipients: "Tất cả người nhận",
      readyToSendFilter: "Sẵn sàng gửi",
      alreadySent: "Đã gửi",
      missingEmailFilter: "Thiếu Email",
      missingCertificateFilter: "Thiếu chứng chỉ",
      recipients: "Người nhận",
      selected: "đã chọn",
      selectAll: "Chọn tất cả",
      deselectAll: "Bỏ chọn tất cả",
      student: "Học sinh",
      email: "Email",
      award: "Giải thưởng",
      status: "Trạng thái",
      missing: "Thiếu",
      ready: "Sẵn sàng",
      pending: "Đang chờ",
      emailComposer: "Soạn Email",
      composeMessage: "Soạn nội dung email của bạn",
      emailTemplate: "Mẫu email",
      defaultTemplate: "Mẫu mặc định",
      formalTemplate: "Mẫu trang trọng",
      friendlyTemplate: "Mẫu thân thiện",
      subjectLine: "Tiêu đề",
      messageBody: "Nội dung",
      availableMergeTags: "Thẻ trộn có sẵn",
      studentName: "Tên đầy đủ học sinh",
      awardReceived: "Giải thưởng nhận được",
      competitionSubject: "Môn thi",
      certificateLink: "Link tới chứng chỉ",
      schoolName: "Trường của học sinh",
      competitionName: "Tên cuộc thi",
      sendAsAttachment: "Gửi dưới dạng đính kèm",
      attachPdfDirectly: "Đính kèm PDF trực tiếp vào email",
      sendAsDriveLink: "Gửi dưới dạng link Drive",
      includeDriveLink: "Bao gồm link Google Drive",
      ccOrganizer: "CC ban tổ chức",
      sendCopyToAdmin: "Gửi bản sao cho admin",
      previewEmail: "Xem trước Email",
      saveTemplate: "Lưu mẫu",
      sendTestEmail: "Gửi Email thử",
      sendToSelected: "Gửi cho đã chọn",
      sendToAllReady: "Gửi cho tất cả sẵn sàng",
      emailPreview: "Xem trước Email",
      previewWithSample: "Xem trước với giá trị mẫu",
      to: "Đến",
      subject: "Tiêu đề",
    },
    logs: {
      title: "Nhật ký",
      subtitle: "Theo dõi tất cả hoạt động tự động",
      searchLogs: "Tìm nhật ký...",
      export: "Xuất",
      processed: "Đã xử lý",
      successful: "Thành công",
      failed: "Thất bại",
      warnings: "Cảnh báo",
      activityLogs: "Nhật ký hoạt động",
      detailedAuditTrail: "Dấu vết kiểm tra chi tiết của tất cả thao tác",
      processingLogs: "Nhật ký xử lý",
      uploadLogs: "Nhật ký tải lên",
      sheetUpdateLogs: "Nhật ký cập nhật Sheet",
      emailLogs: "Nhật ký Email",
      errorsOnly: "Chỉ lỗi",
      timestamp: "Thời gian",
      action: "Hành động",
      studentName: "Tên học sinh",
      certCode: "Mã chứng chỉ",
      result: "Kết quả",
      details: "Chi tiết",
      actions: "Hành động",
      success: "Thành công",
      warning: "Cảnh báo",
      studentProcessingTimeline: "Dòng thời gian xử lý học sinh",
      completeAuditTrail: "Dấu vết kiểm tra đầy đủ cho",
      certificateMatched: "Đã ghép chứng chỉ",
      matchedWithHighConfidence: "Đã ghép với độ tin cậy cao với hồ sơ học sinh",
      uploadedToDrive: "Đã tải lên Drive",
      fileUploadedSuccessfully: "File đã được tải lên Google Drive thành công",
      sheetUpdated: "Đã cập nhật Sheet",
      fileUrlWrittenToSheet: "URL file đã được ghi vào Google Sheets hàng",
      emailSent: "Đã gửi Email",
      certificateEmailSent: "Email chứng chỉ đã gửi tới",
    },
    settings: {
      title: "Cài đặt",
      subtitle: "Cấu hình hành vi hệ thống và tích hợp",
      fileNaming: "Đặt tên File",
      matchingRules: "Quy tắc ghép",
      validation: "Xác thực",
      integrations: "Tích hợp",
      fileNamingRules: "Quy tắc đặt tên File",
      configureFileNames: "Cấu hình cách đặt tên file chứng chỉ",
      prettyFormat: "Định dạng tên file đẹp",
      prettyFormatDesc: "Dùng để hiển thị. Hỗ trợ: {student_name}, {award}, {subject}, {school}, {grade}, {cert_code}",
      safeFormat: "Định dạng tên file an toàn",
      safeFormatDesc: "Dùng để lưu trữ thực tế. Ký tự đặc biệt sẽ tự động bị xóa.",
      maxFileLength: "Độ dài tên file tối đa",
      characters: "ký tự",
      transliterateVietnamese: "Chuyển ký tự tiếng Việt",
      transliterateVietnameseDesc: "Chuyển \"Nguyễn\" thành \"Nguyen\", \"Đỗ\" thành \"Do\", v.v.",
      replaceSpaces: "Thay khoảng trắng bằng gạch dưới",
      replaceSpacesDesc: "Tương thích hơn với một số hệ thống",
      convertToLowercase: "Chuyển sang chữ thường",
      convertToLowercaseDesc: "Tất cả tên file đều chữ thường",
      saveFileNamingRules: "Lưu quy tắc đặt tên file",
      studentMatchingRules: "Quy tắc ghép học sinh",
      howToMatchCertificates: "Cách ghép chứng chỉ với hồ sơ học sinh",
      exactCertCodeMatch: "Ghép chính xác mã chứng chỉ",
      exactCertCodeMatchDesc: "Ghép theo mã chứng chỉ khi có sẵn",
      exactStudentIdMatch: "Ghép chính xác mã học sinh",
      exactStudentIdMatchDesc: "Ghép theo mã học sinh khi không có mã chứng chỉ",
      fuzzyNameMatch: "Ghép tên học sinh mờ",
      fuzzyNameMatchDesc: "Cho phép lỗi chính tả nhỏ",
      verifyAwardSubject: "Xác minh giải thưởng và môn",
      verifyAwardSubjectDesc: "Phải khớp với giải thưởng và môn dự kiến",
      confidenceThreshold: "Ngưỡng độ tin cậy",
      confidenceThresholdDesc: "Điểm độ tin cậy tối thiểu để tự động duyệt ghép",
      fuzzyMatchTolerance: "Dung sai ghép mờ",
      fuzzyMatchToleranceDesc: "Độ tương đồng chuỗi cần thiết cho ghép tên mờ",
      saveMatchingRules: "Lưu quy tắc ghép",
      validationRules: "Quy tắc xác thực",
      detectCommonErrors: "Phát hiện lỗi và bất thường phổ biến",
      detectTypoQualified: "Phát hiện lỗi chính tả \"Qualifed\" (Thiếu 'i')",
      detectTypoQualifiedDesc: "Lỗi OCR phổ biến trong văn bản chứng chỉ",
      detectCaseAnomalies: "Phát hiện bất thường chữ hoa/thường",
      detectCaseAnomaliesDesc: "Đánh dấu viết hoa không nhất quán",
      detectSchoolPipe: "Phát hiện tên trường chứa \"|\"",
      detectSchoolPipeDesc: "Lỗi OCR phổ biến cho \"l\" hoặc \"I\"",
      detectMissingAward: "Phát hiện thiếu giải thưởng",
      detectMissingAwardDesc: "Chứng chỉ không có thông tin giải thưởng",
      detectDuplicateFiles: "Phát hiện tên file trùng lặp",
      detectDuplicateFilesDesc: "Cảnh báo xung đột ghi đè tiềm ẩn",
      detectDuplicateCertCode: "Phát hiện mã chứng chỉ trùng lặp",
      detectDuplicateCertCodeDesc: "Cùng mã được dùng cho nhiều chứng chỉ",
      checkMissingEmail: "Kiểm tra địa chỉ Email thiếu",
      checkMissingEmailDesc: "Đánh dấu học sinh không có email trước khi gửi",
      validateEmailFormat: "Xác thực định dạng Email",
      validateEmailFormatDesc: "Kiểm tra địa chỉ email được định dạng đúng",
      saveValidationRules: "Lưu quy tắc xác thực",
      googleDriveApi: "Google Drive API",
      configureDriveIntegration: "Cấu hình tích hợp Google Drive",
      clientId: "Client ID",
      clientSecret: "Client Secret",
      redirectUri: "Redirect URI",
      testConnection: "Kiểm tra kết nối",
      googleSheetsApi: "Google Sheets API",
      configureSheetsIntegration: "Cấu hình tích hợp Google Sheets",
      apiKey: "API Key",
      serviceAccountEmail: "Email tài khoản dịch vụ",
      gmailEmailService: "Gmail / Dịch vụ Email",
      configureEmailService: "Cấu hình dịch vụ gửi email",
      serviceType: "Loại dịch vụ",
      gmailApi: "Gmail API",
      googleAppsScript: "Google Apps Script",
      sendGrid: "SendGrid",
      smtp: "SMTP",
      fromEmail: "Email gửi",
      fromName: "Tên người gửi",
      webhookEndpoint: "Webhook Endpoint",
      optionalWebhook: "Webhook tùy chọn cho tích hợp bên ngoài",
      webhookUrl: "URL Webhook",
      secretKey: "Khóa bí mật",
      enableWebhook: "Bật Webhook",
      sendEventsToExternal: "Gửi sự kiện đến endpoint bên ngoài",
      saveIntegrationSettings: "Lưu cài đặt tích hợp",
    },
    common: {
      ago: "trước",
      minute: "phút",
      minutes: "phút",
      hour: "giờ",
      hours: "giờ",
      day: "ngày",
      days: "ngày",
    },
  },
};
