# Generated by Django 6.0.3 on 2026-03-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        ("data_imports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_student_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("school_name", models.CharField(blank=True, max_length=255)),
                (
                    "normalized_school_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("grade", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["full_name", "external_student_id"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_row_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("subject", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("sheet_row_key", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="competitions.competition",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "competition",
                    "source_row_number",
                    "participant__full_name",
                ],
                "unique_together": {("competition", "participant")},
            },
        ),
        migrations.CreateModel(
            name="CompetitionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("award", models.CharField(blank=True, max_length=120)),
                (
                    "certificate_code",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("qualified_round", models.CharField(blank=True, max_length=120)),
                ("imported_source", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="participants.competitionenrollment",
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="data_imports.dataimportjob",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "competition_enrollment__source_row_number",
                    "certificate_code",
                    "pk",
                ],
            },
        ),
    ]
