# Generated by Django 6.0.3 on 2026-03-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionenrollment",
            name="source_data_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
