# Generated by Django 6.0.3 on 2026-03-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
        ("participants", "0003_competitionenrollment_source_sheet_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="competitionenrollment",
            unique_together={("competition", "participant", "subject")},
        ),
    ]
