# Generated by Django 6.0.3 on 2026-03-26 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        ("participants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificatePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                (
                    "split_pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="certificate_pages/%Y/%m/%d/"
                    ),
                ),
                (
                    "preview_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificate_previews/%Y/%m/%d/",
                    ),
                ),
                ("output_filename", models.CharField(blank=True, max_length=255)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("split", "Split"),
                            ("extracted", "Extracted"),
                            ("matched", "Matched"),
                            ("review_required", "Review Required"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("has_text_layer", models.BooleanField(default=False)),
                ("drive_file_id", models.CharField(blank=True, max_length=255)),
                ("drive_file_url", models.URLField(blank=True)),
                (
                    "sheet_write_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("updated", "Updated"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("updated", "Updated"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["source_batch", "page_number"],
            },
        ),
        migrations.CreateModel(
            name="CertificateMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence_score", models.FloatField(default=0)),
                (
                    "confidence_label",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                (
                    "matched_by",
                    models.CharField(
                        choices=[
                            ("certificate_code", "Certificate Code"),
                            ("student_id", "Student ID"),
                            ("fuzzy_name", "Fuzzy Name"),
                            ("manual", "Manual"),
                            ("unmatched", "Unmatched"),
                        ],
                        default="unmatched",
                        max_length=32,
                    ),
                ),
                ("requires_review", models.BooleanField(default=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rationale", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_matches",
                        to="participants.competitionenrollment",
                    ),
                ),
                (
                    "competition_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_matches",
                        to="participants.competitionresult",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "certificate_page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match",
                        to="certificates.certificatepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificateExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("ocr", "OCR"),
                            ("text_plus_ocr", "Text + OCR"),
                        ],
                        default="text",
                        max_length=32,
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("competition_name", models.CharField(blank=True, max_length=255)),
                ("student_name", models.CharField(blank=True, max_length=255)),
                (
                    "normalized_student_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("school_name", models.CharField(blank=True, max_length=255)),
                (
                    "normalized_school_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("award", models.CharField(blank=True, max_length=120)),
                ("subject", models.CharField(blank=True, max_length=120)),
                (
                    "certificate_code",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("qualified_round", models.CharField(blank=True, max_length=120)),
                ("warnings_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate_page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction",
                        to="certificates.certificatepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourcePdfBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(upload_to="source_batches/%Y/%m/%d/"),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("page_count", models.PositiveIntegerField(default=0)),
                (
                    "inferred_competition_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "confirmed_competition_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "competition_confirmation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("overridden", "Overridden"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "processing_mode",
                    models.CharField(
                        choices=[
                            ("split_only", "Split Only"),
                            ("split_extract", "Split + Extract"),
                            ("split_extract_match", "Split + Extract + Match"),
                            ("full_pipeline", "Full Pipeline"),
                        ],
                        default="split_extract_match",
                        max_length=32,
                    ),
                ),
                ("options_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("awaiting_confirmation", "Awaiting Confirmation"),
                            ("ready", "Ready"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pdf_batches",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="certificatepage",
            name="source_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="certificates.sourcepdfbatch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certificatepage",
            unique_together={("source_batch", "page_number")},
        ),
    ]
