# Generated by Django 6.0.3 on 2026-03-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateextraction",
            name="grade",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="certificatepage",
            name="public_slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="certificatepage",
            name="public_url",
            field=models.URLField(blank=True),
        ),
    ]
