# Generated by Django 6.0.3 on 2026-03-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimportjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("inspected", "Inspected"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
