# Generated by Django 6.0.3 on 2026-03-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("academic_year", models.CharField(blank=True, max_length=100)),
                (
                    "competition_type",
                    models.CharField(
                        choices=[
                            ("olympiad", "Olympiad"),
                            ("contest", "Contest"),
                            ("exam", "Exam"),
                            ("fair", "Fair"),
                            ("other", "Other"),
                        ],
                        default="contest",
                        max_length=32,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=120)),
                (
                    "email_template_subject",
                    models.CharField(blank=True, max_length=255),
                ),
                ("email_template_body", models.TextField(blank=True)),
                (
                    "folder_naming_rule",
                    models.CharField(default="{competition}_{year}", max_length=255),
                ),
                (
                    "file_naming_rule",
                    models.CharField(
                        default="{student_name}_{award}_{subject}.pdf", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "academic_year"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheets_spreadsheet_id", models.CharField(blank=True, max_length=255)),
                ("sheets_worksheet_name", models.CharField(blank=True, max_length=255)),
                ("sheets_credentials_json", models.TextField(blank=True)),
                ("drive_folder_id", models.CharField(blank=True, max_length=255)),
                ("drive_folder_url", models.URLField(blank=True)),
                ("gmail_sender", models.EmailField(blank=True, max_length=254)),
                ("is_sheets_connected", models.BooleanField(default=False)),
                ("is_drive_connected", models.BooleanField(default=False)),
                ("is_email_connected", models.BooleanField(default=False)),
                ("last_sheets_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_drive_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_email_check_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_config",
                        to="competitions.competition",
                    ),
                ),
            ],
        ),
    ]
